#
# Module manifest for module 'SecretsManagement.VMware.CloudFoundation'
#
# Generated by: erikgraa
#
# Generated on: 05/09/2025
#

@{
    ModuleVersion = '0.2505.7'
    CompatiblePSEditions = @('Core')
    GUID = '7c61c156-3408-41a0-a91d-fd1913398680'
    Author = 'erikgraa'
    Copyright = 'Copyright (c) 2025 erikgraa, licensed under the MIT License.'
    Description = 'A Cross-Platform SecretManagement Vault extension for VMware Cloud Foundation.'
    PowerShellVersion = '7.4'

    NestedModules = @('./SecretManagement.VMware.CloudFoundation.Extension')

    RequiredModules = @('Microsoft.Powershell.SecretManagement')

    PrivateData = @{
        PSData = @{
            Tags = @(
                'Cross-Platform', 'PowerShell', 'PowerShell-Core', 'Secret', 'SecretManagement',
                'Vault', 'VaultExtension', 'VMware'
            )

            ProjectUri     = 'https://github.com/erikgraa/SecretManagement.VMware.CloudFoundation'
            LicenseUri     = 'https://github.com/erikgraa/SecretManagement.VMware.CloudFoundation/blob/main/LICENSE'
            IconUri        = 'https://raw.githubusercontent.com/erikgraa/SecretManagement.VMware.CloudFoundation/refs/heads/main/images/logo.png'
            ReleaseNotes   = 'https://github.com/erikgraa/SecretManagement.VMware.CloudFoundation'
        }
    }
}